apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: produccion
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "r00tpass"
  MYSQL_DATABASE: "fleetdb"
  MYSQL_USER: "fleetuser"
  MYSQL_PASSWORD: "fleetpass"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: produccion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11
          envFrom:
            - secretRef:
                name: mariadb-secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 15
            periodSeconds: 5
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: produccion
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
