# values-grafana.yml — Helm chart: grafana/grafana
adminPassword: "admin"

persistence:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server
        access: proxy
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        options:
          path: /var/lib/grafana/dashboards

grafana.ini:
  alerting:
    enabled: true
  unified_alerting:
    enabled: false
